export const ADDRESS_SAVE_REQUEST = "ADDRESS_SAVE_REQUEST";
export const ADDRESS_SAVE_SUCCESS = "ADDRESS_SAVE_SUCCESS";
export const ADDRESS_SAVE_FAIL = "ADDRESS_SAVE_FAIL";

export const PAYMENT_METHOD_SAVE = "PAYMENT_METHOD_SAVE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

